---
# tasks file for docker

- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: /home/opstree/Documents/Docker/
    name: jfrog
    tag: v1
    push: yes
    source: build
