---
# tasks file for jenkins
- name: Update
  apt:
    update_cache: yes

- name: Install openjdk
  apt:
    name: openjdk-8-jdk
    state: present

- name: Set environment variable of JAVA
  shell: echo "JAVA_HOME"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

- name: Import GPG keys of the Jenkins Repository 
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add jenkins repo to the system
  command: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Update
  apt:
    update_cache: yes
    state: build-dep

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    force_apt_get: yes
    dpkg_options: 'force-confold,force-confdef'

- name: Status
  systemd:
    name: jenkins
    state: started

- name: Allow port 8080
  ufw:
    rule: allow
    port: 8080
    proto: tcp


