---
# tasks file for git
- name: Update
  apt: 
    update_cache: yes

- name: Install git
  apt:
    name: git
    state: present

- git_config:
    name: user.name
    scope: global
    value: Arpita

- git_config:
    name: user.email
    scope: global
    value: arpitasrivastava1424@gmail.com