---
# tasks file for maven
- name: Update
  apt:
    update_cache: yes

- name: Unarchive 
  unarchive:
    src: https://www-us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    dest: /opt
    remote_src: yes

- name: Create the symlink
  file:
    src: /opt/apache-maven-3.6.3
    dest: /opt/maven
    state: link

- name: Set environment variable
  shell: echo "M2_HOME"
  environment: 
    M2_HOME: /opt/maven

